In [2]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import ipywidgets as widgets
import plotly.graph_objects as go
from plotly.offline import iplot

In [ ]:
df_emt = pd.read_csv("data\emt.csv", sep = ";")
df_emt.head()

,Id. Parada,Cod. Via / Cod. Vía,Num. Portal,Suprimida,Denominació / Denominación,Línies / Líneas,Pròximes Arribades / Proximas Llegadas,geo_shape,geo_point_2d
0,397.0,NaN,59,0,Felipe Valls - Lluís Cano (397),"62,N3",http://www.emtvalencia.es/QR.php?sec=est&p=397,"{""coordinates"": [-0.4191237742755592, 39.50142...","39.501427898376356, -0.4191237742755592"
1,948.0,NaN,62,0,Tavernes Blanques (948),"16,N2",http://www.emtvalencia.es/QR.php?sec=est&p=948,"{""coordinates"": [-0.3654941003557221, 39.50687...","39.5068784141963, -0.3654941003557221"
2,475.0,12180.0,3,0,Brasil - Artur Piera (475),73,http://www.emtvalencia.es/QR.php?sec=est&p=475,"{""coordinates"": [-0.3951866421883474, 39.47071...","39.47071907570776, -0.3951866421883474"
3,484.0,18390.0,108,0,Cid - Passatge Vidal (484),"70,93,N4",http://www.emtvalencia.es/QR.php?sec=est&p=484,"{""coordinates"": [-0.4032098687744392, 39.46960...","39.46960970393574, -0.4032098687744392"
4,495.0,18390.0,85,0,Cid - Marconi (495),"93,98",http://www.emtvalencia.es/QR.php?sec=est&p=495,"{""coordinates"": [-0.4132110636422129, 39.46923...","39.469233328598364, -0.4132110636422129"

In [17]:
df_metro = pd.read_csv(r"data\fgv_bocas.csv", sep = ";")
df_metro.head()

,gid,Denominació / Denominación,Línies / Líneas,Id. Parada,Id. Boca,Pròximes Arribades / Próximas llegadas,proximes_llegadas,geo_shape,geo_point_2d
0,182,FOIOS,3,6,215,https://geoportal.valencia.es/geoportal-servic...,https://geoportal.valencia.es/geoportal-servic...,"{""coordinates"": [-0.353869438543834, 39.537223...","39.5372238152284, -0.353869438543834"
1,187,RAFELBUNYOL,3,1,220,https://geoportal.valencia.es/geoportal-servic...,https://geoportal.valencia.es/geoportal-servic...,"{""coordinates"": [-0.33105832383704287, 39.5885...","39.588523863986794, -0.33105832383704287"
2,22,Á. GIMERÁ,"1,3,5,9",17,3,https://geoportal.valencia.es/geoportal-servic...,https://geoportal.valencia.es/geoportal-servic...,"{""coordinates"": [-0.38410946248914607, 39.4695...","39.46959137449779, -0.38410946248914607"
3,11,ARAGÓN,"5,7",24,13,https://geoportal.valencia.es/geoportal-servic...,https://geoportal.valencia.es/geoportal-servic...,"{""coordinates"": [-0.3577954459515307, 39.47269...","39.47269126027633, -0.3577954459515307"
4,6,AMISTAT,"5,7",23,11,https://geoportal.valencia.es/geoportal-servic...,https://geoportal.valencia.es/geoportal-servic...,"{""coordinates"": [-0.3518176379178333, 39.47074...","39.47074908629906, -0.3518176379178333"

In [111]:
df_metro.loc[df_metro.loc[:,'Denominació / Denominación'] ==  'PATRAIX']

,gid,Denominació / Denominación,Línies / Líneas,Id. Parada,Id. Boca,Pròximes Arribades / Próximas llegadas,proximes_llegadas,geo_shape,geo_point_2d
19,64,PATRAIX,"1,3,7",26,85,https://geoportal.valencia.es/geoportal-servic...,https://geoportal.valencia.es/geoportal-servic...,"{""coordinates"": [-0.39043208680578856, 39.4567...","39.45670893544153, -0.39043208680578856"
51,65,PATRAIX,"1,3,7",26,86,https://geoportal.valencia.es/geoportal-servic...,https://geoportal.valencia.es/geoportal-servic...,"{""coordinates"": [-0.39050544918856134, 39.4560...","39.45604416765922, -0.39050544918856134"

In [ ]:
df_metro_zona1 = df_metro.loc[(df_metro.loc[:, "Línies / Líneas"] == '5,7') | (df_metro.loc[:, "Línies / Líneas"] == '4,6')].groupby('Denominació / Denominación')['Línies / Líneas'].value_counts().reset_index()
df_metro_zona1.iloc[:,0:2]

   Denominació / Denominación Línies / Líneas
0                     AMISTAT             5,7
1                      ARAGÓN             5,7
2                       AYORA             5,7
3                   DR. LLUCH             4,6
4               EUGENIA VIÑES             4,6
5                   LA CADENA             4,6
6                 LA CARRASCA             4,6
7                   LA MARINA             4,6
8                  LES ARENES             4,6
9                PRIMADO REIG             4,6
10                   SERRERÍA             4,6
11                  TARONGERS             4,6
12    UNIVERSITAT POLITÈCNICA             4,6
13                V. ZARAGOZÁ             4,6

In [113]:
df_metro_zona2 = df_metro.loc[(df_metro.loc[:, "Línies / Líneas"] == '1,3,7')].groupby('Denominació / Denominación')['Línies / Líneas'].value_counts().reset_index()
df_metro_zona2.iloc[:,0:2]

  Denominació / Denominación Línies / Líneas
0                   HOSPITAL           1,3,7
1            JOAQUÍN SOROLLA           1,3,7
2                   PAIPORTA           1,3,7
3                    PATRAIX           1,3,7
4                    PICANYA           1,3,7
5                SANT ISIDRE           1,3,7
6                    TORRENT           1,3,7
7           TORRENT AVINGUDA           1,3,7
8               VALENCIA SUD           1,3,7

In [95]:
df_metro.loc[df_metro.loc[:,'Denominació / Denominación'] == "LA CARRASCA"]

,gid,Denominació / Denominación,Línies / Líneas,Id. Parada,Id. Boca,Pròximes Arribades / Próximas llegadas,proximes_llegadas,geo_shape,geo_point_2d
138,89,LA CARRASCA,"4,6",88,122,https://geoportal.valencia.es/geoportal-servic...,https://geoportal.valencia.es/geoportal-servic...,"{""coordinates"": [-0.34482499991390064, 39.4796...","39.479660033513994, -0.34482499991390064"

In [ ]:
df_colegios = pd.read_csv("data\centros-educativos-en-valencia.csv", sep = ";")
df_colegios = df_colegios.loc[(df_colegios.loc[:,"regimen"] == 'PÚBLICO') & (df_colegios.loc[:,"municipio_"] == 'València') & (df_colegios["dlibre"].str.startswith("CEIP"))]
df_colegios_groupby = df_colegios.groupby('codpos').size().reset_index(name='num_colegios').sort_values(by = 'num_colegios',ascending = False)
df_colegios_groupby

    codpos  num_colegios
18   46022             9
13   46017             7
14   46018             6
10   46014             6
15   46019             5
7    46011             5
2    46006             4
11   46015             4
17   46021             4
22   46026             3
20   46024             3
19   46023             3
9    46013             3
5    46009             3
6    46010             2
3    46007             2
8    46012             2
23   46035             2
21   46025             2
4    46008             2
16   46020             2
1    46004             1
0    46003             1
12   46016             1
24   46112             1

In [64]:
df_barrios = pd.read_csv(r"data\barris-barrios.csv", sep = ";")
df_barrios

,Codigo distrito-barrio,Nombre,Codigo distrito,Codigo barrio,Areas de barrios,geo_point_2d,geo_shape
0,133,L'AMISTAT,13,3,207274.85938,"39.47266145515942, -0.3510313310016864","{""coordinates"": [[[-0.3525380336296802, 39.475..."
1,111,EL GRAU,11,1,NaN,"39.44375401975586, -0.3237063132818091","{""coordinates"": [[[-0.33283277458056865, 39.42..."
2,175,RAFALELL-VISTABELLA,17,5,NaN,"39.55880504953868, -0.3031699565111558","{""coordinates"": [[[-0.2876696850267751, 39.556..."
3,135,LA CARRASCA,13,5,NaN,"39.48035805242704, -0.3410905938386986","{""coordinates"": [[[-0.3315104329274244, 39.485..."
4,182,BENIFERRI,18,2,NaN,"39.49619604837128, -0.4057172459247872","{""coordinates"": [[[-0.41243901132539496, 39.49..."
...,...,...,...,...,...,...,...
83,193,PINEDO,19,3,NaN,"39.406290326215334, -0.33967854582733203","{""coordinates"": [[[-0.3501774078804209, 39.422..."
84,192,CASTELLAR-L'OLIVERAL,19,2,NaN,"39.427159561794234, -0.359258525330681","{""coordinates"": [[[-0.37228588408947955, 39.42..."
85,191,EL FORN D'ALCEDO,19,1,NaN,"39.43246749635461, -0.3782011306971909","{""coordinates"": [[[-0.3886781972888568, 39.433..."
86,121,AIORA,12,1,651213.25000,"39.46573283778115, -0.34335984023183136","{""coordinates"": [[[-0.3483563963597515, 39.469..."
87,105,NA ROVELLA,10,5,540119.62500,"39.452899854094944, -0.36593196673398615","{""coordinates"": [[[-0.35838674005755433, 39.45..."

In [74]:
df_parques = pd.read_csv(r"data\zones-jocs-infantils-zona-juegos-infantiles.csv", sep = ";")
df_parques.loc[:,"Barrio"].unique()

array(['La Malva-Rosa', 'Betero', 'Cabanyal-Canyamelar', 'El Grau',
       'Aiora', 'Penya-Roja', 'Cami Fondo', 'La Vega Baixa',
       "L'Illa Perduda", 'Les Tendetes', 'Sant Pau', 'Campanar',
       'Benicalap', 'Trinitat', 'Morvedre', 'Marxalenes', 'Sant Antoni',
       'Ciutat Universitaria', 'Mestalla', 'La Carrasca', 'Cami de Vera',
       'Benimaclet', 'Els Orriols', 'Soternes', 'Nou Moles',
       'Tres Forques', 'La Llum', 'Vara de Quart', 'Favara',
       'Sant Isidre', 'Safranar', 'Sant Marceli', "L'Hort de Senabre",
       'Mont-Olivet', 'Malilla', 'Torrefiel', 'Sant Llorens', 'Borboto',
       'Poble Nou', 'Carpesa', 'Benifaraig', 'El Carme', 'El Mercat',
       'El Pilar', 'La Gran Via', 'Russafa', 'Arrancapins', 'El Botanic',
       'Ciutat Jardi', "L'Amistat", 'La Fontsanta', 'Patraix',
       'Na Rovella', 'Ciutat Fallera', 'La Punta', 'Natzaret',
       'Benimamet', 'Cauce del Turia',
       'Ciutat de les Arts i de les Ciencies', 'La Torre',
       "Castellar-L'Oliveral", 'Faitanar', 'El Palmar', 'Pinedo',
       'Cami Real', 'Beniferri', 'La Petxina', 'Albors',
       'La Creu del Grau', 'Tormos', 'La Raiosa', 'La Creu Coberta',
       'En Corts', 'La Fonteta de San Luis', 'Massarrojos',
       'Sant Francesc', 'La Xerea', 'Exposicio', "El Forn d'Alcedo",
       'La Roqueta', 'El Saler'], dtype=object)

In [ ]:
df_zona1 = df_parques.loc[(df_parques.loc[:, "Barrio"] == 'Betero') |  (df_parques.loc[:, "Barrio"] == 'La Carrasca')]
df_zona2 = df_parques.loc[(df_parques.loc[:, "Barrio"] == 'La Torre') |  (df_parques.loc[:, "Barrio"] == 'Sant Marceli')]
df_zona3 = df_parques.loc[(df_parques.loc[:, "Barrio"] == 'Tres Forques') | (df_parques.loc[:, "Barrio"] == 'La Fuensanta')]

In [90]:
df_zona1.loc[:,"Barrio"] = 'Betero y La Carrasca'
df_zona2.loc[:, "Barrio"] = 'La Torre y Sant Marceli'
df_zona3.loc[:,"Barrio"] = 'Tres Forques y La Fuensanta'